name: build docker image

on:
  push:
    tags:
      - v* 

jobs:
  build-docker-image:
    name: Build And Push Docker Image
    strategy:
      matrix:
        os: [ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:

      - name: Checkout Code Base
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: |
          sudo apt-get install -y tar libsnappy-dev
          mkdir build

      - name: Set ENV
        run: echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push Docker Image
        run: |
          make -j4
          cp src/kvrocks build/kvrocks
          docker build -t bitleak/kvrocks:$RELEASE_TAG .
          docker tag bitleak/kvrocks:$RELEASE_TAG bitleak/kvrocks:latest
          docker push bitleak/kvrocks:$RELEASE_TAG
          docker push bitleak/kvrocks:latest

