name: release linux packages and docker image

on:
  push:
    tags:
      - v*

env:
  FPM_OPTS: "-s dir --prefix '/www/kvrocks' -n kvrocks --epoch 7 \
          --config-files /www/kvrocks/conf/kvrocks.conf --iteration release \
          --verbose --category 'bitleak/projects' --description 'kvrocks' \
          --url 'https://github.com/bitleak' --license 'BSD'"

jobs:
  release-deb-packages-and-docker-image:
    name: Release Deb Packages And Docker Image
    runs-on: ubuntu-18.04
    steps:

      - name: Checkout Code Base
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 64

      - name: Install Dependencies
        run: |
          sudo apt-get install -y tar libsnappy-dev
          mkdir -p build/bin
          mkdir -p build/conf

      - name: Build
        run: |
          make -j4
          cp src/kvrocks build/bin/
          cp src/kvrocks2redis build/bin/
          cp kvrocks.conf build/conf/

      - name: Set ENV
        run: |
          echo "RELEASE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Package Deb
        uses: bpicode/github-action-fpm@v0.9.2
        with:
          fpm_args: '.'
          fpm_opts: '-t deb -v ${{ env.VERSION }} -C ./build --depends libsnappy-dev ${{ env.FPM_OPTS }}'

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build And Push Docker Image
        run: |
          docker build -t bitleak/kvrocks:$RELEASE_TAG .
          docker tag bitleak/kvrocks:$RELEASE_TAG bitleak/kvrocks:latest
          docker push bitleak/kvrocks:$RELEASE_TAG
          docker push bitleak/kvrocks:latest

  release-rpm-packages:
    name: Release Rpm Packages
    runs-on: ubuntu-18.04
    container: centos:7
    steps:

      - name: Install Dependencies
        run: |
          yum install -y epel-release
          yum install -y https://packages.endpoint.com/rhel/7/os/x86_64/endpoint-repo-1.7-1.x86_64.rpm
          yum install -y git gcc gcc-c++ make snappy snappy-devel autoconf automake libtool which gtest gtest-devel

      - name: Checkout Code Base
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 64

      - name: Build
        run: |
          make -j4
          mkdir -p build/bin
          mkdir -p build/conf
          cp src/kvrocks build/bin/
          cp src/kvrocks2redis build/bin/
          cp kvrocks.conf build/conf/

      - name: Set ENV
        run: |
          echo "VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Package Rpm
        uses: bpicode/github-action-fpm@v0.9.2
        with:
          fpm_args: '.'
          fpm_opts: "-t rpm -v ${{ env.VERSION }} -C ./build --depends snappy ${{ env.FPM_OPTS }}"

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



