name: run ci without jemalloc

on:
  pull_request:
    types: [labeled]

jobs:
  build-on-ubuntu-without-jemalloc:
    strategy:
      matrix:
        os: [ubuntu-18.04]
    
    if: ${{ github.event.label.name == 'run ci without jemalloc' }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code Base
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 64

      - name: Build
        run: |
          git submodule init && git submodule update
          mkdir _build && cd _build
          cmake -DDISABLE_JEMALLOC=true -DCMAKE_BUILD_TYPE=Release ..
          make -j4 kvrocks kvrocks2redis
          cp kvrocks ../src && cd ..

      - name: Redis Tcl Test
        run: |
          sudo apt-get install tcl8.5
          cd tests/tcl && sh runtest && cd -
